### ISSUE TITLE
slow range resolution

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [barchart/barchart-maven-karaf-plugin#5]
Also, try running "mvn install" on instance/feed-01. It takes a loooooong time. Not sure if that's unavoidable or if it's something you want to track down in the feature generator. Not a showstopper, just thought you'd want to know/see it.

-j

**Comment by Andrei-Pozolotin** [comment]
No, that sounds too scary.

Is there a way to have your plugin respect the --update-snapshots setting? i.e. only use local cache unless it is too old, or the user specifies --update-snapshots?

-j

**Comment by jjongsma** [comment]
Data point: feed-01 instance just took 6 minutes to build a feature repository (12 minutes total for a release because of prepare/perform)
